# Generated by Django 2.1.4 on 2018-12-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Origin Country',
                'verbose_name_plural': 'Origin Countries',
                'db_table': 'country',
                'ordering': ['country_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('province_id', models.AutoField(primary_key=True, serialize=False)),
                ('province_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Origin Province',
                'verbose_name_plural': 'Origin Provinces',
                'db_table': 'province',
                'ordering': ['province_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region1',
            fields=[
                ('region1_id', models.AutoField(primary_key=True, serialize=False)),
                ('region1_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Origin Region1',
                'verbose_name_plural': 'Origin Region1',
                'db_table': 'region1',
                'ordering': ['region1_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region2',
            fields=[
                ('region2_id', models.AutoField(primary_key=True, serialize=False)),
                ('region2_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Origin Region2',
                'verbose_name_plural': 'Origin Region2',
                'db_table': 'region2',
                'ordering': ['region2_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Taster',
            fields=[
                ('taster_id', models.AutoField(primary_key=True, serialize=False)),
                ('taster_name', models.CharField(max_length=100, unique=True)),
                ('taster_twitter_handle', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Taster',
                'verbose_name_plural': 'Taster',
                'db_table': 'taster',
                'ordering': ['taster_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('variety_id', models.AutoField(primary_key=True, serialize=False)),
                ('variety_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Variety',
                'verbose_name_plural': 'Varieties',
                'db_table': 'variety',
                'ordering': ['variety_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('wine_id', models.AutoField(primary_key=True, serialize=False)),
                ('wine_name', models.CharField(max_length=200, unique=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Wine',
                'verbose_name_plural': 'Wines',
                'db_table': 'wine',
                'ordering': ['wine_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WineReview',
            fields=[
                ('wine_review_id', models.AutoField(primary_key=True, serialize=False)),
                ('description_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Wine _ Review',
                'verbose_name_plural': 'Wine _ Review',
                'db_table': 'wine_review',
                'ordering': ['wine', 'taster'],
                'managed': False,
            },
        ),
    ]
